#!/bin/bash

if [[ ! -d logs ]]; then
    mkdir logs
fi

killall emailer
python3 emailer.py server &
disown %python3

sudo killall gunicorn
sudo gunicorn \
    --bind localhost:8000 \
    --workers 2 \
    --reload \
    --access-logfile "logs/accesslog_$(date --iso-8601)" \
    --error-logfile "logs/errorlog_$(date --iso-8601)" \
    app:app &

disown %sudo
