#!/bin/bash
if [[ -z "$1" ]]; then
    read -sp 'Server password: ' password
    echo
else
    password=$1
fi

formatter='\
    from urllib import parse;\
    import sys;\
    print(parse.quote_plus(" ".join(sys.argv[1:])))'

read -p 'Liuid: ' liuid

echo "Field to modify:"
echo "1. Name"
echo "2. Email"
echo "3. Join date"
echo "4. Renewed date"
echo "5. Subscription"
read -p '> ' choice

case $choice in
    1)
        field="name"
        ;;

    2)
        field="email"
        ;;

    3)
        field="joined"
        ;;

    4)
        field="renewed"
        ;;

    5)
        field="receive_email"
        ;;

    *)
        echo "Invalid choice."
        exit 1
        ;;
esac

read -p 'New value: ' new
new=$(python3 -c "${formatter}" $new)

curl -u :$password "lithekod.lysator.liu.se/modify/?id=$liuid&field=$field&new=$new"
echo
