name: run-tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install
        run: |
          pip install -r requirements.txt
          git clone https://github.com/lithekod/emails
      - name: Run tests
        run: |
          python test.py
